[package]
name = "entity_deserializer"
version = "0.1.0"
authors = ["Bob <bobcn.me@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
regex = "1.3.4"
